### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by AhnMo** [KAIST-IS521/2018s-onion-team5#18]
- [ ] Server name validation issue. #15
 - [ ] UI history chatlog limitation. #16
 - [ ] Messenger send_message connection check. #17
